### ISSUE TITLE
Roadmap for version 0.1

### ISSUE THREAD

**Issue by kanatti** [kanatti/opensearch-arrow#1]
## Overview
- Arrow Java API
- What can arrow do? What are the arrow best practices?
- Data format and memory layout.
- Opensearch plugin architecture, lifecycle and extension points
- Implementation
	- Basic Plugin Structure
	- Reproduce basic query life cycle.
	- Integrate with arrow
	- Optimize
	- Profiling
	- Failure handling, backpressure, streaming
	- GRPC?
	- Per shard parallelism? Arrow flight?

TODO
- [x] Setup
  - [x] Setup Repo with Gradle
  - [x] Plugin setup
  - [x] Test cluster with plugin installed.
- [ ] Query Life Cycle
  - [ ] Accept a query and run it and return response

**Comment by kanatti** [comment]
## Plugin resources
- https://opensearch.org/blog/my-first-steps-in-opensearch-plugins/
- https://opensearch.org/blog/plugins-intro/
- https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md
- https://github.com/opensearch-project/opensearch-plugin-template-java


## Arrow resources
- https://arrow.apache.org/docs/java/index.html
- https://arrow.apache.org/cookbook/java/
- https://www.infoq.com/articles/apache-arrow-java/
- https://github.com/animeshtrivedi/blog/blob/master/post/2017-12-26-arrow.md

**Comment by kanatti** [comment]
Reference plugins
- https://github.com/opensearch-project/opensearch-plugins
- https://github.com/opensearch-project/neural-search
- https://github.com/opensearch-project/asynchronous-search
- https://github.com/opensearch-project/job-scheduler
- https://github.com/opensearch-project/custom-codecs/tree/main

How to run the plugin on a different port - https://github.com/opensearch-project/performance-analyzer

**Comment by kanatti** [comment]
How to run the plugin on a different port - https://github.com/opensearch-project/performance-analyzer
